import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: [
        '/',
        '/sign-up',
        '/sign-in',
        '/pricing',
        '/docusign-alternative',
        '/docusign-vs-boopsign',
        '/hellosign-alternative',
        '/zoho-sign-alternative',
        '/online-signature-maker',
        '/mobile-electronic-signature',
        '/no-account-esignature',
        '/privacy-policy',
        '/adobe-sign-alternative',
        '/dropbox-sign-alternative',
        '/pandadoc-alternative',
        '/signnow-alternative',
        '/signrequest-alternative',
        '/proposal-signing-software',
        '/freelance-contract-template',
        '/electronic-signature-laws',
        '/esignature-vs-digital-signature',
        '/how-to-create-electronic-signature',
        '/contract-signing-best-practices',
        '/document-security-guide',
        '/nda-template-free',
        '/consulting-agreement-template',
        '/client-onboarding-documents',
        '/remote-team-document-signing',
        '/real-estate-document-signing',
        '/hr-document-signing',
        '/education-document-signing',
        '/esignature-for-consultants',
        '/esignature-for-freelancers',
        '/fintech-document-signing',
        '/healthcare-document-signing',
        '/guides/3-minute-freelance-workflow',
        '/guides/why-clients-hate-esignature',
        '/guides/esignature-cost-comparison'
      ],
      disallow: [
        '/dashboard/',
        '/d/',
        '/d/*',
        '/s/',
        '/s/*',
        '/api/',
        '/api/*',
        '/account/billing/',
        '/complete/',
        '/callback'
      ],
    },
    sitemap: 'https://www.boopsign.com/sitemap.xml',
  }
}
