// Template variable definitions for each contract template

export interface TemplateVariable {
  key: string;
  label: string;
  required: boolean;
  type?: "text" | "email" | "number" | "currency" | "date" | "textarea";
  placeholder?: string;
  defaultValue?: string;
}

export interface TemplateConfig {
  id: string;
  name: string;
  variables: TemplateVariable[];
  fileUrl: string;
}

export const templateVariables: Record<string, TemplateConfig> = {
  "social-media-management-contract": {
    id: "social-media-management-contract",
    name: "Social Media Management Contract",
    fileUrl: "https://2d9wfb370a.ufs.sh/f/X2DTqAlZ9PgubTqTZAOYpiuVWJNbYakZKvysf0TlQOLdtcSG",
    variables: [
      {
        key: "start_date",
        label: "Contract Start Date",
        required: true,
        type: "date",
      },
      {
        key: "client_name",
        label: "Client Name",
        required: true,
        type: "text",
        placeholder: "e.g., John Smith or ABC Company",
      },
      {
        key: "client_address",
        label: "Client Address",
        required: true,
        type: "text",
        placeholder: "123 Main St, City, State, ZIP",
      },
      {
        key: "client_email",
        label: "Client Email",
        required: true,
        type: "email",
        placeholder: "client@example.com",
      },
      {
        key: "client_phone",
        label: "Client Phone",
        required: false,
        type: "text",
        placeholder: "(555) 123-4567",
      },
      {
        key: "agency_name",
        label: "Your Agency Name",
        required: true,
        type: "text",
        placeholder: "e.g., Digital Marketing Agency",
      },
      {
        key: "agency_address",
        label: "Your Agency Address",
        required: true,
        type: "text",
        placeholder: "456 Business Ave, City, State, ZIP",
      },
      {
        key: "agency_email",
        label: "Your Agency Email",
        required: true,
        type: "email",
        placeholder: "agency@example.com",
      },
      {
        key: "agency_phone",
        label: "Your Agency Phone",
        required: false,
        type: "text",
        placeholder: "(555) 987-6543",
      },
      {
        key: "posts_per_week",
        label: "Posts per Week",
        required: true,
        type: "number",
        placeholder: "5",
      },
      {
        key: "platforms",
        label: "Social Media Platforms",
        required: true,
        type: "text",
        placeholder: "Instagram, LinkedIn, Twitter",
      },
      {
        key: "monthly_fee",
        label: "Monthly Service Fee",
        required: true,
        type: "currency",
        placeholder: "1500",
      },
      {
        key: "hourly_rate",
        label: "Hourly Rate (Additional Services)",
        required: false,
        type: "currency",
        placeholder: "75",
      },
      {
        key: "payment_method",
        label: "Payment Method",
        required: false,
        type: "text",
        placeholder: "Credit Card, Bank Transfer, Check",
        defaultValue: "Credit Card or Bank Transfer",
      },
      {
        key: "payment_due_day",
        label: "Payment Due Day",
        required: false,
        type: "text",
        placeholder: "1st or 15th",
        defaultValue: "1st",
      },
      {
        key: "late_fee_percentage",
        label: "Late Fee Percentage",
        required: false,
        type: "number",
        placeholder: "5",
        defaultValue: "5",
      },
      {
        key: "content_submission_day",
        label: "Content Calendar Submission Day",
        required: false,
        type: "text",
        placeholder: "5th",
        defaultValue: "5th",
      },
      {
        key: "approval_days",
        label: "Client Approval Days",
        required: false,
        type: "number",
        placeholder: "3",
        defaultValue: "3",
      },
      {
        key: "revision_rounds",
        label: "Revision Rounds Included",
        required: false,
        type: "number",
        placeholder: "2",
        defaultValue: "2",
      },
      {
        key: "governing_law",
        label: "Governing Law",
        required: false,
        type: "text",
        placeholder: "California, USA",
      },
    ],
  },

  "wedding-photography-contract": {
    id: "wedding-photography-contract",
    name: "Wedding Photography Contract",
    fileUrl: "https://2d9wfb370a.ufs.sh/f/X2DTqAlZ9PguxwuiXgz24etUsO3ZN7hLWQYKjHkDySfFd0cg",
    variables: [
      {
        key: "contract_date",
        label: "Contract Date",
        required: true,
        type: "date",
      },
      {
        key: "wedding_date",
        label: "Wedding Date",
        required: true,
        type: "date",
      },
      {
        key: "ceremony_time",
        label: "Ceremony Time",
        required: false,
        type: "text",
        placeholder: "3:00 PM",
      },
      {
        key: "ceremony_venue",
        label: "Ceremony Venue",
        required: true,
        type: "text",
        placeholder: "St. Mary's Church, 123 Church St, City, State",
      },
      {
        key: "reception_venue",
        label: "Reception Venue",
        required: true,
        type: "text",
        placeholder: "Grand Hotel Ballroom, 456 Hotel Ave, City, State",
      },
      {
        key: "couple_names",
        label: "Couple's Names",
        required: true,
        type: "text",
        placeholder: "e.g., John Smith & Jane Doe",
      },
      {
        key: "couple_phone",
        label: "Couple's Phone",
        required: true,
        type: "text",
        placeholder: "(555) 123-4567",
      },
      {
        key: "couple_email",
        label: "Couple's Email",
        required: true,
        type: "email",
        placeholder: "couple@example.com",
      },
      {
        key: "photographer_name",
        label: "Your Name (Photographer)",
        required: true,
        type: "text",
        placeholder: "e.g., Sarah Photography",
      },
      {
        key: "photographer_phone",
        label: "Your Phone",
        required: true,
        type: "text",
        placeholder: "(555) 987-6543",
      },
      {
        key: "photographer_email",
        label: "Your Email",
        required: true,
        type: "email",
        placeholder: "photographer@example.com",
      },
      {
        key: "hours_coverage",
        label: "Hours of Coverage",
        required: true,
        type: "number",
        placeholder: "8",
      },
      {
        key: "start_time",
        label: "Coverage Start Time",
        required: false,
        type: "text",
        placeholder: "2:00 PM",
      },
      {
        key: "end_time",
        label: "Coverage End Time",
        required: false,
        type: "text",
        placeholder: "10:00 PM",
      },
      {
        key: "num_photographers",
        label: "Number of Primary Photographers",
        required: false,
        type: "number",
        placeholder: "1",
        defaultValue: "1",
      },
      {
        key: "num_assistants",
        label: "Number of Assistant Photographers",
        required: false,
        type: "number",
        placeholder: "0",
        defaultValue: "0",
      },
      {
        key: "min_photos",
        label: "Minimum Edited Photos",
        required: false,
        type: "number",
        placeholder: "400",
      },
      {
        key: "additional_services",
        label: "Additional Services",
        required: false,
        type: "text",
        placeholder: "Engagement session, photo album",
      },
      {
        key: "package_price",
        label: "Total Package Price",
        required: true,
        type: "currency",
        placeholder: "3500",
      },
      {
        key: "retainer_amount",
        label: "Booking Retainer Amount",
        required: true,
        type: "currency",
        placeholder: "1000",
      },
      {
        key: "retainer_due_date",
        label: "Retainer Due Date",
        required: false,
        type: "date",
      },
      {
        key: "second_payment",
        label: "Second Payment Amount",
        required: false,
        type: "currency",
        placeholder: "1250",
      },
      {
        key: "second_payment_date",
        label: "Second Payment Due Date",
        required: false,
        type: "date",
      },
      {
        key: "final_balance",
        label: "Final Balance",
        required: false,
        type: "currency",
        placeholder: "1250",
      },
      {
        key: "payment_methods",
        label: "Payment Methods Accepted",
        required: false,
        type: "text",
        placeholder: "Check, Wire Transfer, Credit Card",
        defaultValue: "Check, Wire Transfer, Credit Card",
      },
      {
        key: "preview_weeks",
        label: "Preview Gallery (Weeks)",
        required: false,
        type: "number",
        placeholder: "2",
        defaultValue: "2",
      },
      {
        key: "delivery_weeks",
        label: "Final Delivery (Weeks)",
        required: false,
        type: "number",
        placeholder: "6",
        defaultValue: "6",
      },
      {
        key: "backup_months",
        label: "Backup Storage (Months)",
        required: false,
        type: "number",
        placeholder: "12",
        defaultValue: "12",
      },
      {
        key: "usage_restrictions",
        label: "Image Usage Restrictions",
        required: false,
        type: "text",
        placeholder: "None, or specify restrictions",
        defaultValue: "None",
      },
      {
        key: "governing_law",
        label: "Governing Law",
        required: false,
        type: "text",
        placeholder: "California, USA",
      },
    ],
  },

  "freelance-contract": {
    id: "freelance-contract",
    name: "Freelance Contract",
    fileUrl: "https://2d9wfb370a.ufs.sh/f/X2DTqAlZ9PguPzgVkmiFW6gqf8SA9UosI1PZnQc5tLJGb7dh",
    variables: [
      {
        key: "start_date",
        label: "Contract Start Date",
        required: true,
        type: "date",
      },
      {
        key: "client_name",
        label: "Client Name",
        required: true,
        type: "text",
        placeholder: "e.g., ABC Company",
      },
      {
        key: "client_address",
        label: "Client Address",
        required: true,
        type: "text",
        placeholder: "123 Main St, City, State, ZIP",
      },
      {
        key: "client_email",
        label: "Client Email",
        required: true,
        type: "email",
        placeholder: "client@example.com",
      },
      {
        key: "freelancer_name",
        label: "Your Name (Freelancer)",
        required: true,
        type: "text",
        placeholder: "e.g., John Smith",
      },
      {
        key: "freelancer_address",
        label: "Your Address",
        required: true,
        type: "text",
        placeholder: "456 Oak St, City, State, ZIP",
      },
      {
        key: "freelancer_email",
        label: "Your Email",
        required: true,
        type: "email",
        placeholder: "freelancer@example.com",
      },
      {
        key: "project_name",
        label: "Project Name",
        required: false,
        type: "text",
        placeholder: "Website Redesign Project",
      },
      {
        key: "project_description",
        label: "Project Description",
        required: true,
        type: "textarea",
        placeholder: "Detailed description of the project scope and deliverables",
      },
      {
        key: "completion_date",
        label: "Completion Date",
        required: false,
        type: "date",
      },
      {
        key: "milestones",
        label: "Key Milestones",
        required: false,
        type: "textarea",
        placeholder: "Milestone 1: Design mockups - Due: [Date]\nMilestone 2: Development - Due: [Date]",
      },
      {
        key: "project_fee",
        label: "Total Project Fee",
        required: true,
        type: "currency",
        placeholder: "5000",
      },
      {
        key: "payment_terms",
        label: "Payment Schedule",
        required: true,
        type: "text",
        placeholder: "50% upfront, 50% on completion",
      },
      {
        key: "payment_method",
        label: "Payment Method",
        required: false,
        type: "text",
        placeholder: "Bank Transfer, PayPal, Check",
      },
      {
        key: "hourly_rate",
        label: "Hourly Rate (Additional Work)",
        required: false,
        type: "currency",
        placeholder: "85",
      },
      {
        key: "revision_rounds",
        label: "Revision Rounds Included",
        required: false,
        type: "number",
        placeholder: "2",
        defaultValue: "2",
      },
      {
        key: "termination_notice_days",
        label: "Termination Notice (Days)",
        required: false,
        type: "number",
        placeholder: "14",
        defaultValue: "14",
      },
      {
        key: "governing_law",
        label: "Governing Law",
        required: false,
        type: "text",
        placeholder: "California, USA",
      },
    ],
  },

  "consulting-agreement": {
    id: "consulting-agreement",
    name: "Consulting Agreement",
    fileUrl: "https://2d9wfb370a.ufs.sh/f/X2DTqAlZ9PguI1w2PMKk6Tt8dN4Y3JApShGWkZ0n9cfeF1v5",
    variables: [
      {
        key: "start_date",
        label: "Agreement Start Date",
        required: true,
        type: "date",
      },
      {
        key: "client_name",
        label: "Client Name",
        required: true,
        type: "text",
        placeholder: "e.g., XYZ Corporation",
      },
      {
        key: "client_address",
        label: "Client Address",
        required: true,
        type: "text",
        placeholder: "123 Corporate Blvd, City, State, ZIP",
      },
      {
        key: "consultant_name",
        label: "Your Name (Consultant)",
        required: true,
        type: "text",
        placeholder: "e.g., Jane Consultant LLC",
      },
      {
        key: "consultant_address",
        label: "Your Address",
        required: true,
        type: "text",
        placeholder: "456 Business Ave, City, State, ZIP",
      },
      {
        key: "scope_of_work",
        label: "Scope of Work",
        required: true,
        type: "textarea",
        placeholder: "Describe the consulting services you'll provide in detail",
      },
      {
        key: "hourly_rate",
        label: "Hourly Rate",
        required: true,
        type: "currency",
        placeholder: "200",
      },
      {
        key: "estimated_hours",
        label: "Estimated Hours",
        required: false,
        type: "number",
        placeholder: "40",
      },
      {
        key: "payment_terms",
        label: "Payment Terms",
        required: false,
        type: "text",
        placeholder: "Net 30 days",
        defaultValue: "Net 30 days",
      },
      {
        key: "termination_notice_days",
        label: "Termination Notice (Days)",
        required: false,
        type: "number",
        placeholder: "30",
        defaultValue: "30",
      },
      {
        key: "governing_law",
        label: "Governing Law",
        required: false,
        type: "text",
        placeholder: "California, USA",
      },
    ],
  },

  "house-cleaning-service-agreement": {
    id: "house-cleaning-service-agreement",
    name: "House Cleaning Service Agreement",
    fileUrl: "https://2d9wfb370a.ufs.sh/f/X2DTqAlZ9PguvGsQgVFrDWmTOdj06ypF5EAP8KuJIs4Cnzwq",
    variables: [
      {
        key: "start_date",
        label: "Agreement Start Date",
        required: true,
        type: "date",
      },
      {
        key: "client_name",
        label: "Client Name",
        required: true,
        type: "text",
        placeholder: "e.g., John & Mary Smith",
      },
      {
        key: "service_address",
        label: "Service Address",
        required: true,
        type: "text",
        placeholder: "123 Main St, City, State, ZIP",
      },
      {
        key: "client_phone",
        label: "Client Phone",
        required: true,
        type: "text",
        placeholder: "(555) 123-4567",
      },
      {
        key: "client_email",
        label: "Client Email",
        required: true,
        type: "email",
        placeholder: "client@example.com",
      },
      {
        key: "business_name",
        label: "Your Business Name",
        required: true,
        type: "text",
        placeholder: "e.g., Sparkle Clean Services",
      },
      {
        key: "provider_phone",
        label: "Your Business Phone",
        required: false,
        type: "text",
        placeholder: "(555) 987-6543",
      },
      {
        key: "service_frequency",
        label: "Service Frequency",
        required: true,
        type: "text",
        placeholder: "Weekly, Bi-weekly, or Monthly",
      },
      {
        key: "scheduled_time",
        label: "Scheduled Day/Time",
        required: false,
        type: "text",
        placeholder: "Mondays at 10:00 AM",
      },
      {
        key: "service_fee",
        label: "Service Fee",
        required: true,
        type: "currency",
        placeholder: "150",
      },
      {
        key: "payment_method",
        label: "Payment Method",
        required: false,
        type: "text",
        placeholder: "Cash, Check, Credit Card",
        defaultValue: "Cash, Check, or Credit Card",
      },
      {
        key: "payment_due",
        label: "Payment Due",
        required: false,
        type: "text",
        placeholder: "Upon completion",
        defaultValue: "Upon completion",
      },
      {
        key: "cancellation_hours",
        label: "Cancellation Notice (Hours)",
        required: false,
        type: "number",
        placeholder: "24",
        defaultValue: "24",
      },
      {
        key: "governing_law",
        label: "Governing Law",
        required: false,
        type: "text",
        placeholder: "California, USA",
      },
    ],
  },

  "nda-template": {
    id: "nda-template",
    name: "Non-Disclosure Agreement (NDA)",
    fileUrl: "https://2d9wfb370a.ufs.sh/f/X2DTqAlZ9PguAM9SZCUIaF7cPRXTBKUOjd2u8DtqMsNepfz5",
    variables: [
      {
        key: "effective_date",
        label: "Effective Date",
        required: true,
        type: "date",
      },
      {
        key: "party1_name",
        label: "First Party Name",
        required: true,
        type: "text",
        placeholder: "e.g., ABC Company Inc.",
      },
      {
        key: "party1_address",
        label: "First Party Address",
        required: true,
        type: "text",
        placeholder: "123 Business St, City, State, ZIP",
      },
      {
        key: "party2_name",
        label: "Second Party Name",
        required: true,
        type: "text",
        placeholder: "e.g., XYZ Corporation",
      },
      {
        key: "party2_address",
        label: "Second Party Address",
        required: true,
        type: "text",
        placeholder: "456 Corporate Ave, City, State, ZIP",
      },
      {
        key: "business_purpose",
        label: "Purpose of Agreement",
        required: true,
        type: "textarea",
        placeholder: "e.g., Exploring a potential partnership, discussing a business acquisition",
      },
      {
        key: "term_years",
        label: "Agreement Term (Years)",
        required: false,
        type: "number",
        placeholder: "3",
        defaultValue: "3",
      },
      {
        key: "confidentiality_years",
        label: "Confidentiality Duration (Years)",
        required: false,
        type: "number",
        placeholder: "5",
        defaultValue: "5",
      },
      {
        key: "governing_law",
        label: "Governing Law",
        required: false,
        type: "text",
        placeholder: "Delaware, USA",
      },
    ],
  },

  "client-onboarding-information-form": {
    id: "client-onboarding-information-form",
    name: "Client Onboarding - Information Form",
    fileUrl: "https://2d9wfb370a.ufs.sh/f/X2DTqAlZ9PguSS7HbvNZ0JQVfwoRLU2NgHxFSv8KIcjdC5i4",
    variables: [
      {
        key: "client_name",
        label: "Full Name",
        required: true,
        type: "text",
        placeholder: "John Smith",
      },
      {
        key: "company_name",
        label: "Company Name",
        required: false,
        type: "text",
        placeholder: "ABC Company Inc.",
      },
      {
        key: "job_title",
        label: "Job Title",
        required: false,
        type: "text",
        placeholder: "CEO, Marketing Director",
      },
      {
        key: "email",
        label: "Email Address",
        required: true,
        type: "email",
        placeholder: "client@example.com",
      },
      {
        key: "phone",
        label: "Phone Number",
        required: true,
        type: "text",
        placeholder: "(555) 123-4567",
      },
      {
        key: "address",
        label: "Address",
        required: false,
        type: "text",
        placeholder: "123 Main St, City, State, ZIP",
      },
      {
        key: "website",
        label: "Website",
        required: false,
        type: "text",
        placeholder: "www.example.com",
      },
      {
        key: "services_interested",
        label: "Services Interested In",
        required: true,
        type: "text",
        placeholder: "Web Design, SEO, Marketing",
      },
      {
        key: "project_goals",
        label: "Project Goals",
        required: true,
        type: "textarea",
        placeholder: "Describe what you want to achieve with this project",
      },
      {
        key: "budget_range",
        label: "Budget Range",
        required: false,
        type: "text",
        placeholder: "$10,000 - $25,000",
      },
      {
        key: "start_date",
        label: "Desired Start Date",
        required: false,
        type: "date",
      },
      {
        key: "completion_date",
        label: "Target Completion Date",
        required: false,
        type: "date",
      },
    ],
  },

  "client-onboarding-services-agreement": {
    id: "client-onboarding-services-agreement",
    name: "Client Onboarding - Services Agreement",
    fileUrl: "https://2d9wfb370a.ufs.sh/f/X2DTqAlZ9Pgu5cwytsHE1vmLZ9tcWbUpQFkC6oT2IPYBjgnH",
    variables: [
      {
        key: "agreement_date",
        label: "Agreement Date",
        required: true,
        type: "date",
      },
      {
        key: "provider_name",
        label: "Service Provider Name",
        required: true,
        type: "text",
        placeholder: "Your Company Name",
      },
      {
        key: "client_name",
        label: "Client Name",
        required: true,
        type: "text",
        placeholder: "Client's Name or Company",
      },
      {
        key: "services_description",
        label: "Services Description",
        required: true,
        type: "textarea",
        placeholder: "Describe the services to be provided",
      },
      {
        key: "start_date",
        label: "Service Start Date",
        required: true,
        type: "date",
      },
      {
        key: "end_date",
        label: "Service End Date",
        required: false,
        type: "date",
      },
      {
        key: "total_fee",
        label: "Total Fee",
        required: true,
        type: "currency",
        placeholder: "15000",
      },
      {
        key: "payment_terms",
        label: "Payment Terms",
        required: true,
        type: "text",
        placeholder: "50% upfront, 50% on completion",
      },
    ],
  },

  "client-onboarding-payment-authorization": {
    id: "client-onboarding-payment-authorization",
    name: "Client Onboarding - Payment Authorization",
    fileUrl: "https://2d9wfb370a.ufs.sh/f/X2DTqAlZ9PgunTaC2MqPKoD3HWzv2hlrfdwZFGRcps6UX9EY",
    variables: [
      {
        key: "client_name",
        label: "Client Name",
        required: true,
        type: "text",
        placeholder: "John Smith",
      },
      {
        key: "authorization_date",
        label: "Authorization Date",
        required: true,
        type: "date",
      },
      {
        key: "payment_method",
        label: "Payment Method",
        required: true,
        type: "text",
        placeholder: "Credit Card, ACH, Check",
      },
      {
        key: "authorized_amount",
        label: "Authorized Amount",
        required: true,
        type: "currency",
        placeholder: "5000",
      },
      {
        key: "company_name",
        label: "Company Name (Authorized to Charge)",
        required: true,
        type: "text",
        placeholder: "Your Company Name",
      },
      {
        key: "cardholder_name",
        label: "Cardholder Name",
        required: false,
        type: "text",
        placeholder: "Name on card",
      },
      {
        key: "card_last_4",
        label: "Card Last 4 Digits",
        required: false,
        type: "text",
        placeholder: "1234",
      },
      {
        key: "billing_address",
        label: "Billing Address",
        required: false,
        type: "text",
        placeholder: "123 Main St, City, State, ZIP",
      },
    ],
  },

  "remote-team-work-agreement": {
    id: "remote-team-work-agreement",
    name: "Remote Team - Work Agreement",
    fileUrl: "https://2d9wfb370a.ufs.sh/f/X2DTqAlZ9PguRbwEbi2w50fPqjJsYVv8Q9nzZRtHkXOiBLDN",
    variables: [
      {
        key: "employee_name",
        label: "Employee Name",
        required: true,
        type: "text",
        placeholder: "John Smith",
      },
      {
        key: "job_title",
        label: "Job Title",
        required: true,
        type: "text",
        placeholder: "Software Engineer",
      },
      {
        key: "department",
        label: "Department",
        required: false,
        type: "text",
        placeholder: "Engineering",
      },
      {
        key: "remote_location",
        label: "Remote Work Location",
        required: true,
        type: "text",
        placeholder: "City, State or Country",
      },
      {
        key: "effective_date",
        label: "Effective Date",
        required: true,
        type: "date",
      },
      {
        key: "working_hours",
        label: "Standard Working Hours",
        required: true,
        type: "text",
        placeholder: "9:00 AM - 5:00 PM",
      },
      {
        key: "timezone",
        label: "Time Zone",
        required: true,
        type: "text",
        placeholder: "EST, PST, UTC",
      },
      {
        key: "core_hours",
        label: "Core Hours (Must be Available)",
        required: false,
        type: "text",
        placeholder: "10:00 AM - 3:00 PM EST",
      },
      {
        key: "communication_tools",
        label: "Communication Tools",
        required: false,
        type: "text",
        placeholder: "Slack, Zoom, Email",
        defaultValue: "Slack, Zoom, Email",
      },
      {
        key: "response_time",
        label: "Expected Response Time",
        required: false,
        type: "text",
        placeholder: "2 hours",
        defaultValue: "2 hours during work hours",
      },
      {
        key: "equipment_provided",
        label: "Company-Provided Equipment",
        required: false,
        type: "text",
        placeholder: "Laptop, Monitor, Headset",
      },
      {
        key: "notice_period",
        label: "Notice Period for Changes (Days)",
        required: false,
        type: "number",
        placeholder: "30",
        defaultValue: "30",
      },
    ],
  },

  "remote-team-equipment-checklist": {
    id: "remote-team-equipment-checklist",
    name: "Remote Team - Equipment Checklist",
    fileUrl: "https://2d9wfb370a.ufs.sh/f/X2DTqAlZ9PguvIGT5hrDWmTOdj06ypF5EAP8KuJIs4CnzwqY",
    variables: [
      {
        key: "employee_name",
        label: "Employee Name",
        required: true,
        type: "text",
        placeholder: "John Smith",
      },
      {
        key: "issue_date",
        label: "Equipment Issue Date",
        required: true,
        type: "date",
      },
      {
        key: "laptop_model",
        label: "Laptop Model",
        required: false,
        type: "text",
        placeholder: "MacBook Pro 16-inch",
      },
      {
        key: "laptop_serial",
        label: "Laptop Serial Number",
        required: false,
        type: "text",
        placeholder: "C02XYZ123456",
      },
      {
        key: "monitor_model",
        label: "Monitor Model",
        required: false,
        type: "text",
        placeholder: 'Dell UltraSharp 27"',
      },
      {
        key: "monitor_serial",
        label: "Monitor Serial Number",
        required: false,
        type: "text",
        placeholder: "CN-ABC123-XYZ",
      },
      {
        key: "additional_equipment",
        label: "Additional Equipment",
        required: false,
        type: "textarea",
        placeholder: "Keyboard, Mouse, Webcam, Headset, Docking Station",
      },
      {
        key: "software_access",
        label: "Software Access Provided",
        required: false,
        type: "textarea",
        placeholder: "Microsoft 365, Slack, VPN Access, GitHub, Jira",
      },
    ],
  },
};

// Helper function to get template config
export function getTemplateConfig(templateId: string): TemplateConfig | null {
  return templateVariables[templateId] || null;
}

// Helper function to format currency
export function formatCurrency(value: string): string {
  const num = parseFloat(value);
  if (isNaN(num)) return value;
  return `$${num.toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

// Helper function to format date
export function formatDate(dateString: string): string {
  const date = new Date(dateString);
  if (isNaN(date.getTime())) return dateString;
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}